/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SortableEntry } from "./components/sortable/sortable";
export namespace Components {
    interface DSortable {
        "entries": SortableEntry[];
    }
}
declare global {
    interface HTMLDSortableElement extends Components.DSortable, HTMLStencilElement {
    }
    var HTMLDSortableElement: {
        prototype: HTMLDSortableElement;
        new (): HTMLDSortableElement;
    };
    interface HTMLElementTagNameMap {
        "d-sortable": HTMLDSortableElement;
    }
}
declare namespace LocalJSX {
    interface DSortable {
        "entries"?: SortableEntry[];
    }
    interface IntrinsicElements {
        "d-sortable": DSortable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "d-sortable": LocalJSX.DSortable & JSXBase.HTMLAttributes<HTMLDSortableElement>;
        }
    }
}
