/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DMarkdown {
        "markdown": string;
    }
}
declare global {
    interface HTMLDMarkdownElement extends Components.DMarkdown, HTMLStencilElement {
    }
    var HTMLDMarkdownElement: {
        prototype: HTMLDMarkdownElement;
        new (): HTMLDMarkdownElement;
    };
    interface HTMLElementTagNameMap {
        "d-markdown": HTMLDMarkdownElement;
    }
}
declare namespace LocalJSX {
    interface DMarkdown {
        "markdown"?: string;
    }
    interface IntrinsicElements {
        "d-markdown": DMarkdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "d-markdown": LocalJSX.DMarkdown & JSXBase.HTMLAttributes<HTMLDMarkdownElement>;
        }
    }
}
